### ISSUE TITLE
Layouts: warn of Percentage is more than 100 or less than 100

### ISSUE THREAD

**Issue by imsnif** [mosaic-org/mosaic#52]
When defining layouts (for example with the `--layout path/to/layout.yaml` flag), we can define them using percentage. For example like this:

```yaml
---
direction: Horizontal
parts:
  - direction: Vertical
    parts:
      - direction: Horizontal
        split_size:
          Percent: 20
      - direction: Horizontal
        split_size:
          Percent: 80
    split_size:
      Percent: 80
  - direction: Vertical
    split_size:
      Percent: 20
```

When parsing this file, we should get an error if the sum of a certain parts array is larger or smaller than 100%.
